name: Case 1 - All success, infra deploy skipped

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  changes:
    uses: ./.github/workflows/check-changes.yml
    with:
      infra_has_changes: false

  trigger-deploy-infra-test:
    needs: changes
    if: ${{ !cancelled() && needs.changes.outputs.infra == 'true' }}
    uses: ./.github/workflows/success.yml

  trigger-deploy-test:
    needs: trigger-deploy-infra-test
    if: ${{ !cancelled() && !failure() }}
    uses: ./.github/workflows/success.yml

  trigger-smoke-test-test:
    needs: trigger-deploy-test
    if: ${{ !cancelled() && needs.trigger-deploy-test.result == 'success' }}
    uses: ./.github/workflows/success.yml

  trigger-deploy-infra-prod:
    needs: [changes, trigger-smoke-test-test]
    if: ${{ !cancelled() && needs.changes.outputs.infra == 'true' && needs.trigger-smoke-test-test.result == 'success' }}
    uses: ./.github/workflows/success.yml

  trigger-deploy-prod:
    needs: [trigger-deploy-infra-prod]
    if: ${{ !cancelled() && !failure() }}
    uses: ./.github/workflows/success.yml

  trigger-smoke-test-prod:
    needs: trigger-deploy-prod
    if: ${{ !cancelled() && needs.trigger-deploy-prod.result == 'success' }}
    uses: ./.github/workflows/success.yml
